---

- name: Copy build_dns_record script
  copy:
    src: 'build_dns_record.py'
    dest: '/tmp/'

- name: Build dns record
  command: '{{ galaxy_venv_path }}/bin/python
            /tmp/build_dns_record.py
            -i "{{ ansible_default_ipv4.address }}"
            -p "{{ dns_record_prefix }}"
            -s "{{ dns_record_suffix }}"
            -d "{{ dns_record_dot_replacement }}"'
  register: vm_dns_record

- debug:
    msg: '{{ vm_dns_record.stdout }}'

# install certbot with pip in virtualenv with py3
