---
# tasks file for ansible-role-laniakea-cert-fix

- debug:
    msg: '{{ admin_email }}'

- include: certbot.yml

- include: nginx.yml

- debug:
    msg: 'Your Galaxy is now available at: https://{{ vm_dns_record.stdout }}/galaxy'
